hydra:
  run:
    dir: runs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: runs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: config
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiment=mil_240929
    - +logger.wandb.tags=[xprefsl,neffb0d5,lce,dipav1]
    - data/dataset=[mil_241007,mil_ds_fg,mil_dav1]
    - +model/loss@model.loss_cls=ce
    - +model/metrics=[f1_acc,auroc]
    - networks/netB=effb0
    - networks.netC.dropout=0.5
    - optimizer.lr=3e-06
    - trainer.max_epochs=400
    - data.dataset.image_target_size=64
    - data.dataset.image_target_padded_size=128
    - data.dataset.cv_fold=3
  job:
    name: ${task_name}
    chdir: null
    override_dirname: +model/loss@model.loss_cls=ce,+model/metrics=[f1_acc,auroc],data.dataset.cv_fold=3,data.dataset.image_target_padded_size=128,data.dataset.image_target_size=64,data/dataset=[mil_241007,mil_ds_fg,mil_dav1],experiment=mil_240929,networks.netC.dropout=0.5,networks/netB=effb0,optimizer.lr=3e-06,trainer.max_epochs=400
    id: '3'
    num: 3
    config_name: train
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - logger.wandb.tags
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/jwchoi/workspace/bonbid24-jwc
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/jwchoi/workspace/bonbid24-jwc/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: /home/jwchoi/workspace/bonbid24-jwc/runs/bonbidmil-2409/2024-10-10_04-07-11/+model/loss@model.loss_cls=ce,+model/metrics=[f1_acc,auroc],data.dataset.cv_fold=3,data.dataset.image_target_padded_size=128,data.dataset.image_target_size=64,data/dataset=[mil_241007,mil_ds_fg,mil_dav1],experiment=mil_240929,networks.netC.dropout=0.5,networks/netB=effb0,optimizer.lr=3e-06,trainer.max_epochs=400
    choices:
      model/loss@model.loss_cls: ce
      experiment: mil_240929
      seed: default
      paths: default
      logger: wandb
      trainer: default
      model: mil
      scheduler: epoch_cosine
      optimizer: adam
      networks: default_mil
      networks/netC: clf_mlp_ad
      networks/netA: attention256
      networks/netB: effb0
      data: default
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
